### ISSUE TITLE
Client hooks to validate code and commit messages

### ISSUE THREAD

**Issue by Lumycea** [clicepfl/website#17]
Now that we have the actions to lint commit messages, we should setup client-side hooks to:
- [x] Validate commit message
- [x] Check that the code is correctly formatted

**Comment by mochiruntime** [comment]
Small nitpick, but I don't think the `ci` tag (as well as commit type) fits for this issue (and related PR #18)? We should probably tag them with `chore` instead (or maybe `build` although it's not really related to the build system). See [conventional commit types](https://github.com/pvdlg/conventional-changelog-metahub#commit-types) :slightly_smiling_face: 

Regarding code formatting, I think we should use [Prettier](https://prettier.io/). It's rather common and there are some nice community plugins such as https://github.com/trivago/prettier-plugin-sort-imports. We should run it in `--write` mode in the client hooks, and in check mode on the CI.

I'm not sure however how we'll ensure that the config works in all service folders, since they each might initialize their own devcontainer. For instance, Prettier will pickup `.prettierrc` at the root by default, however we need to decide if the config file should be shared (e.g. bind mounts) / copied, but also each service may need to define its own configuration. Linting commits should probably be the same no matter in which part of the hierarchy you may be working.

**Comment by Lumycea** [comment]
> We should run it in `--write` mode in the client hooks

I'm really not a fan of the idea to modify committed code without confirmations. And the modifications would not be in the commit, as they would not be in the index. We would need to get the name of all files in the index (by parsing `git status` output) and run a `git add`

I think having different configurations for different parts of the repository could be both useful and confusing, we'll discuss this

> Linting commits should probably be the same

I agree, all commits will end up at the same place

**Comment by mochiruntime** [comment]
> I'm really not a fan of the idea to modify committed code without confirmations. And the modifications would not be in the commit, as they would not be in the index. We would need to get the name of all files in the index (by parsing `git status` output) and run a `git add`

You're right, makes a lot of sense. Now that I think about it, I've mostly seen it being used in check mode during the pre-commit hook and it would reject the commit with an error message such as "Code style issues found in the above file(s). Forgot to run Prettier?" if the code is not properly formatted (it's probably the default message). I think we could do that too?

**Comment by Lumycea** [comment]
> it's probably the default message

It is. I have already pushed that in #18 ([198b2441ed29bd213b6689043d0a34290d55f708](https://github.com/clicepfl/clic-website-v2/pull/18/commits/198b2441ed29bd213b6689043d0a34290d55f708))

**Comment by mochiruntime** [comment]
Note to self: see https://github.com/clicepfl/clic-website-v2/pull/18#pullrequestreview-1332822358
